"use client";

import { useState } from "react";
import { ArrowRight, BookOpen, Boxes, CircleDot, Clock3, ExternalLink, Github, Menu, Route, ShieldCheck, Sparkles, X, Zap } from "lucide-react";

type Phase = { id:string; number:string; window:string; title:string; summary:string; status:"ready"|"next"|"later"; modules:Array<{title:string;detail:string;docs:Array<[string,string]>}>; exit:string };

const phases:Phase[]=[
 {id:"foundation",number:"01",window:"第 1–2 周",title:"理解资产与搭好地基",summary:"先把 xStocks 的资产模型、Token-2022 行为和开发环境弄对，再写业务逻辑。",status:"ready",modules:[
  {title:"xStocks 资产模型",detail:"读取资产、mint、市场价格与 multiplier；明确受限地区、披露和展示边界。",docs:[["开发者概览","https://docs.xstocks.fi/developers"],["API Reference","https://docs.xstocks.fi/apis/openapi"],["Multiplier","https://docs.xstocks.fi/developers/multipliers"]]},
  {title:"Token-2022 兼容",detail:"识别 Scaled UI Amount 等扩展，显示余额时应用 multiplier，不把 raw amount 当作股票数量。",docs:[["Token Extensions","https://solana.com/docs/tokens/extensions"],["Scaled UI Amount","https://solana.com/docs/tokens/extensions/scaled-ui-amount"]]},
  {title:"本地工作区",detail:"固定 devnet RPC、CLI 钱包与 TypeScript/Rust 版本，建立可复现的 pnpm 与 cargo 工作流。",docs:[["安装工具链","https://solana.com/docs/intro/installation"],["程序开发","https://solana.com/docs/programs"]]}],exit:"能从链上读取指定 xStock mint、扩展与余额，并与 xStocks API 的 multiplier 对账。"},
 {id:"portfolio",number:"02",window:"第 3–4 周",title:"组合数据层与可读界面",summary:"把钱包里的 xStocks 变成可信、可解释的组合视图。",status:"ready",modules:[
  {title:"持仓发现",detail:"按 owner 扫描 Token 与 Token-2022 accounts，过滤官方 mint allowlist，批量读取账户。",docs:[["Token 基础","https://solana.com/docs/tokens/basics"],["账户查询 RPC","https://solana.com/docs/rpc/http/gettokenaccountsbyowner"]]},
  {title:"估值与公司行动",detail:"合并市场价格、decimals 与 multiplier；对拆股、反向拆股和分红建立刷新与缓存策略。",docs:[["xStocks API","https://docs.xstocks.fi/apis/openapi"],["公司行动","https://docs.xstocks.fi/developers/multipliers"]]},
  {title:"Solana 前端",detail:"用 Wallet Standard / Kit 连接钱包，提供网络、空状态、RPC 失败与交易反馈。",docs:[["Frontend 指南","https://solana.com/docs/frontend"],["Next.js 教程","https://solana.com/docs/frontend/nextjs-solana"]]}],exit:"连接钱包后可正确展示持仓、调整后数量、市场价值与数据更新时间。"},
 {id:"trade",number:"03",window:"第 5–7 周",title:"报价与交易执行",summary:"从只读组合升级到可模拟、可签名、可核验的调仓交易。",status:"next",modules:[
  {title:"路由与报价",detail:"通过 Jupiter 获取 exact-in 报价；设置滑点、price impact、mint 白名单与报价过期时间。",docs:[["Jupiter 文档","https://dev.jup.ag/docs"],["Swap API","https://dev.jup.ag/docs/swap"]]},
  {title:"交易构建",detail:"签名前展示输入、最小输出、费用与路由；确认 blockhash、模拟结果和 Token-2022 账户。",docs:[["Solana 交易","https://solana.com/docs/core/transactions"],["发送交易","https://solana.com/docs/rpc/http/sendtransaction"]]},
  {title:"结果核验",detail:"用签名追踪 confirmed/finalized 状态，超时先查询再重试，避免重复成交。",docs:[["确认与过期","https://solana.com/developers/guides/advanced/confirmation"],["签名状态","https://solana.com/docs/rpc/http/getsignaturestatuses"]]}],exit:"devnet 上完成一笔可复现的模拟/测试资产调仓，失败路径不会造成重复提交。"},
 {id:"automation",number:"04",window:"第 8–10 周",title:"策略与自动化控制面",summary:"让策略规则上链、执行服务可替换、每次运行可审计。",status:"next",modules:[
  {title:"Pinocchio 程序",detail:"用 PDA 保存版本化权重、阈值、authority 与状态机；严格校验 signer、owner、seeds 和算术。",docs:[["Pinocchio","https://github.com/anza-xyz/pinocchio"],["PDA","https://solana.com/docs/core/pda"],["CPI","https://solana.com/docs/core/cpi"]]},
  {title:"调仓引擎",detail:"先 paper mode，再开启执行；以偏离带而非固定频率触发，限制单笔和每日换手。",docs:[["本项目 ABI","https://github.com/0xagentlabs/xstocks-portfolio-autopilot/blob/main/docs/ABI.md"],["程序安全","https://solana.com/developers/courses/program-security"]]},
  {title:"调度与幂等",detail:"执行 ID 单调递增；任务重放只回读结果，不重复发单；紧急停止禁止新执行。",docs:[["账户模型","https://solana.com/docs/core/accounts"],["交易生命周期","https://solana.com/docs/core/transactions"]]}],exit:"策略配置、暂停和急停均需 authority 签名；重复 execution ID 在链上被拒绝。"},
 {id:"risk",number:"05",window:"第 11–12 周",title:"行情、风控与可观测性",summary:"任何数据异常都 fail closed，所有关键决策都有证据链。",status:"later",modules:[
  {title:"Oracle 防护",detail:"验证 feed ID、发布时间、置信区间与 staleness；将 oracle、xStocks API、DEX quote 交叉校验。",docs:[["Pyth Price Feeds","https://docs.pyth.network/price-feeds/core/price-feeds"],["Pyth on Solana","https://docs.pyth.network/price-feeds/core/push-feeds/solana"]]},
  {title:"交易风控",detail:"限制滑点、价格影响、单资产权重、每日亏损与 turnover；异常时只允许撤销和暂停。",docs:[["Jupiter 文档","https://dev.jup.ag/docs"],["安全课程","https://solana.com/developers/courses/program-security"]]},
  {title:"监控审计",detail:"记录 quote、simulation、signature、slot、策略版本与触发原因；为 RPC、oracle、成交失败设告警。",docs:[["RPC 方法","https://solana.com/docs/rpc/http"],["日志订阅","https://solana.com/docs/rpc/websocket/logssubscribe"]]}],exit:"过期价格、异常价差、超限调仓和未知 mint 都被拒绝，且告警包含可定位的交易上下文。"},
 {id:"launch",number:"06",window:"第 13 周起",title:"测试、审计与渐进上线",summary:"用明确门禁从 devnet、paper mode 走向受控生产，而不是一次性切换。",status:"later",modules:[
  {title:"测试矩阵",detail:"Rust 单测 + LiteSVM/Mollusk + TypeScript 集成测试，覆盖权限、PDA、畸形数据、溢出和重复执行。",docs:[["LiteSVM","https://github.com/LiteSVM/litesvm"],["Mollusk","https://github.com/anza-xyz/mollusk"]]},
  {title:"安全发布",detail:"完成独立审查，锁定 program ID 与 upgrade authority；先小额、限资产、限用户灰度。",docs:[["部署程序","https://solana.com/docs/programs/deploying"],["程序安全","https://solana.com/developers/courses/program-security"]]},
  {title:"运营与合规",detail:"持续同步 xStocks 法律披露、受限司法辖区与资产清单；前端不暗示股东权利或投资建议。",docs:[["xStocks 文档","https://docs.xstocks.fi/docs"],["FAQ","https://docs.xstocks.fi/docs/frequently-asked-questions"]]}],exit:"审计问题关闭、回滚演练通过、监控与值班就绪，再按资产和额度逐步放量。"}
];
const filters=[["all","全部阶段"],["ready","现在开始"],["next","随后推进"],["later","上线准备"]] as const;

export default function Home(){
 const [filter,setFilter]=useState<(typeof filters)[number][0]>("all"); const [open,setOpen]=useState(false); const visible=filter==="all"?phases:phases.filter(p=>p.status===filter);
 return <main id="main-content"><a className="skip-link" href="#roadmap">跳至路线图</a>
  <nav className="topbar" aria-label="主导航"><a className="brand" href="#top" aria-label="xStocks Dev Path 首页"><span className="brand-mark"><Route aria-hidden="true"/></span><span>xStocks <b>Dev Path</b></span></a><div className={`nav-links ${open?"open":""}`}><a href="#roadmap" onClick={()=>setOpen(false)}>路线图</a><a href="#principles" onClick={()=>setOpen(false)}>设计原则</a><a href="#resources" onClick={()=>setOpen(false)}>资源</a><a className="nav-cta" href="https://github.com/0xagentlabs/xstocks-portfolio-autopilot" target="_blank" rel="noreferrer"><Github aria-hidden="true"/>查看项目</a></div><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?"关闭导航":"打开导航"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></nav>
  <header className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><Sparkles aria-hidden="true"/> SOLANA × TOKENIZED EQUITIES</p><h1>从第一个 mint，走到可审计的 <span>xStocks 应用</span></h1><p className="lede">一条面向工程团队的 13 周开发路径。每个模块都连接到权威文档，并设置明确的退出门禁。</p><div className="hero-actions"><a className="primary" href="#roadmap">开始阅读 <ArrowRight aria-hidden="true"/></a><a className="secondary" href="https://docs.xstocks.fi/developers" target="_blank" rel="noreferrer">xStocks 文档 <ExternalLink aria-hidden="true"/></a></div><p className="updated"><CircleDot aria-hidden="true"/> 文档校验于 2026-09 · 仅供开发规划，不构成投资建议</p></div><div className="hero-map" aria-label="路线图概览"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="map-core"><span>13</span><small>周核心路径</small></div>{phases.map((p,i)=><a key={p.id} href={`#${p.id}`} className={`map-node node-${i+1}`}><b>{p.number}</b><span>{p.title.split("与")[0]}</span></a>)}</div></header>
  <section className="signal-row" aria-label="路线图摘要"><div><b>6</b><span>交付阶段</span></div><div><b>18</b><span>核心模块</span></div><div><b>40+</b><span>文档入口</span></div><div><b>4</b><span>发布门禁</span></div></section>
  <section className="roadmap-section" id="roadmap"><div className="section-heading"><div><p className="eyebrow">BUILD SEQUENCE</p><h2>把复杂系统拆成可验收的阶段</h2><p>点击标签聚焦当前节奏；每个阶段内的链接都指向上游文档。</p></div><div className="filters" aria-label="筛选路线图">{filters.map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)} aria-pressed={filter===v}>{l}</button>)}</div></div><div className="timeline">{visible.map(p=><article className="phase" id={p.id} key={p.id}><div className="phase-rail"><span>{p.number}</span><i/></div><div className="phase-body"><div className="phase-head"><div><span className={`status ${p.status}`}>{p.status==="ready"?"基础":p.status==="next"?"核心":"扩展"}</span><span className="window"><Clock3 aria-hidden="true"/>{p.window}</span><h3>{p.title}</h3><p>{p.summary}</p></div><span className="module-count">{p.modules.length} MODULES</span></div><div className="modules">{p.modules.map(m=><div className="module" key={m.title}><div className="module-icon"><Boxes aria-hidden="true"/></div><h4>{m.title}</h4><p>{m.detail}</p><div className="doc-links">{m.docs.map(([l,h])=><a key={h} href={h} target="_blank" rel="noreferrer"><BookOpen aria-hidden="true"/>{l}<ExternalLink aria-hidden="true"/></a>)}</div></div>)}</div><div className="exit-gate"><span><ShieldCheck aria-hidden="true"/>EXIT GATE</span><p>{p.exit}</p></div></div></article>)}</div></section>
  <section className="principles" id="principles"><div className="section-heading"><div><p className="eyebrow">ENGINEERING PRINCIPLES</p><h2>四条不能后补的底线</h2></div></div><div className="principle-grid">{[["01","Multiplier 优先","Solana raw balance 不会自动反映公司行动；所有展示与估值都必须应用官方 multiplier。"],["02","默认拒绝","未知 mint、过期价格、异常价差或不完整模拟都应停止执行，而不是猜测。"],["03","钱包掌权","策略服务只提出交易，用户 authority、额度和急停规则必须可验证、可撤销。"],["04","先 Paper Mode","用真实数据和虚拟成交跑完整观测周期，再以资产、额度和用户范围渐进开放。"]].map(([n,t,b])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
  <section className="resources" id="resources"><div><p className="eyebrow"><Zap aria-hidden="true"/> START HERE</p><h2>准备好开始第一阶段？</h2><p>先完成资产发现与 multiplier 对账，再进入任何交易或自动化代码。</p></div><div className="resource-actions"><a href="https://docs.xstocks.fi/developers" target="_blank" rel="noreferrer">打开 xStocks 文档 <ExternalLink aria-hidden="true"/></a><a href="https://solana.com/docs/tokens/extensions" target="_blank" rel="noreferrer">理解 Token-2022 <ExternalLink aria-hidden="true"/></a></div></section>
  <footer><a className="brand" href="#top"><span className="brand-mark"><Route aria-hidden="true"/></span><span>xStocks <b>Dev Path</b></span></a><p>Built for engineers shipping responsibly on Solana.</p><span>Devnet first · Verify everything</span></footer>
 </main>;
}
